###############################---eureka---##############################
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}/eureka/
#######e签宝
sign:
  url: https://o.tsign.cn/opentreaty-service
  appId: 4438758707
  appSecret: 3af57b9b79b617d6058839029184a981
  docId: 0e1c106c2cb445c5a58557fb9a35f498
  